### ISSUE TITLE
error in alphas(), something wrong with _tile_or_trim()

### ISSUE THREAD

**Issue by chrislnorth** [jhamrick/plotchecker#9]
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-73-c8dfe0c06f9f> in <module>()
      6 #pc.assert_y_data_equal(y)
      7 #pc.alphas
----> 8 pc.alphas
      9 
     10 

~/anaconda3/lib/python3.6/site-packages/plotchecker/scatterplot.py in alphas(self)
    147                 else:
    148                     alpha = np.array([x.get_alpha()])
--> 149                 all_alphas.append(self._tile_or_trim(points, alpha))
    150 
    151         return np.concatenate(all_alphas)

~/anaconda3/lib/python3.6/site-packages/plotchecker/base.py in _tile_or_trim(cls, x, y)
    129         if xn > yn:
    130             numrep = np.ceil(xn / yn)
--> 131             y = np.tile(y, (numrep,) + (1,) * (y.ndim - 1))
    132             yn = y.shape[0]
    133         if xn < yn:

~/anaconda3/lib/python3.6/site-packages/numpy/lib/shape_base.py in tile(A, reps)
    912                 c = c.reshape(-1, n).repeat(nrep, 0)
    913             n //= dim_in
--> 914     return c.reshape(shape_out)

TypeError: 'numpy.float64' object cannot be interpreted as an integer

**Comment by jhamrick** [comment]
Thanks for reporting this! I've just opened a PR to fix the issue.
